### ISSUE TITLE
snmpsim: ModuleNotFoundError: No module named 'pyasn1.compat.octets'

### ISSUE THREAD

**Issue by Jellyfrog** [lextudio/pysnmp#117]
### Expected behavior

It working :)

### Actual behavior

After pyasn1 releases 0.6.1 it broke snmpsim.
This is the same issue as in https://github.com/lextudio/pysnmp/issues/113

```
$ ./bin/snmpsim-command-responder-lite
Traceback (most recent call last):
  File "/tmp/snmpsim/./bin/snmpsim-command-responder-lite", line 5, in <module>
    from snmpsim.commands.responder_lite import main
  File "/tmp/snmpsim/lib/python3.12/site-packages/snmpsim/commands/responder_lite.py", line 26, in <module>
    from snmpsim import controller
  File "/tmp/snmpsim/lib/python3.12/site-packages/snmpsim/controller.py", line 15, in <module>
    from snmpsim import datafile
  File "/tmp/snmpsim/lib/python3.12/site-packages/snmpsim/datafile.py", line 12, in <module>
    from pyasn1.compat.octets import str2octs
ModuleNotFoundError: No module named 'pyasn1.compat.octets'
```

### Detailed steps

The steps are,

### Python package information

snmpsim==1.1.5

### Operating system information

Linux

### Python information

3.12.3

**Comment by lextm** [comment]
Fixed in release 1.1.6.
