### ISSUE TITLE
bulkCmd KeyError exception

### ISSUE THREAD

**Issue by Noppes** [lextudio/pysnmp#122]
### Expected behavior

I expect to receive (RequestTimedOut('No SNMP response received before timeout'), 0, 0, ()) like with getCmd

### Actual behavior

Instead Im getting KeyError: 'errorIndication'

### Detailed steps

Using bulkCmd on an snmp device with incorrect login credentials gives a KeyError: 'errorIndication' and makes the whole program hang

### Python package information

7.1.3

### Operating system information

Ubuntu

### Python information

3.12

### (Optional) Contents of your test script

```python
snmp_engine = SnmpEngine()
    authData = UsmUserData("admin", authKey="wrongpas", privKey="wrongpas", 
        authProtocol=config.USM_AUTH_HMAC96_MD5, privProtocol=config.USM_PRIV_CBC56_DES)
    result = await bulkCmd(snmp_engine,
        authData,
        await UdpTransportTarget.create(('192.168.3.1', 161), timeout=10, retries=2),
        ContextData(),
        0, 25,
        ObjectType(ObjectIdentity('SNMPv2-MIB', 'system')),
        ObjectType(ObjectIdentity('SNMPv2-MIB', 'sysName')),
        ObjectType(ObjectIdentity('IF-MIB', 'ifDescr')),
        ObjectType(ObjectIdentity('IF-MIB', 'ifType')),
        ObjectType(ObjectIdentity('IF-MIB', 'ifMtu')),
        ObjectType(ObjectIdentity('IF-MIB', 'ifSpeed')),
        ObjectType(ObjectIdentity('IF-MIB', 'ifPhysAddress')),
        lookupMib=True
    )
```

### Relevant log output

```shell
Exception in callback AbstractTransportDispatcher._cbFun(<pysnmp.carri...0014836663820>, ('192.168.3.1', 161), b'0H\x02\x01\...\x01\x000\x00')
handle: <Handle AbstractTransportDispatcher._cbFun(<pysnmp.carri...0014836663820>, ('192.168.3.1', 161), b'0H\x02\x01\...\x01\x000\x00')>
Traceback (most recent call last):
  File "C:\pkservices\docker\.venv\lib\site-packages\pysnmp\proto\rfc3412.py", line 413, in receiveMessage
    ) = mpHandler.prepareDataElements(
  File "C:\pkservices\docker\.venv\lib\site-packages\pysnmp\proto\mpmod\rfc3412.py", line 900, in prepareDataElements
    raise statusInformation
pysnmp.proto.error.StatusInformation: {'sendPduHandle': 1130826}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\pkservices\docker\.venv\lib\site-packages\pysnmp\carrier\base.py", line 142, in _cbFun
    self.__recvCallables[recvId](
  File "C:\pkservices\docker\.venv\lib\site-packages\pysnmp\entity\engine.py", line 221, in __receiveMessageCbFun
    self.msgAndPduDsp.receiveMessage(
  File "C:\pkservices\docker\.venv\lib\site-packages\pysnmp\proto\rfc3412.py", line 430, in receiveMessage
    self.__expireRequest(
  File "C:\pkservices\docker\.venv\lib\site-packages\pysnmp\proto\rfc3412.py", line 685, in __expireRequest
    processResponsePdu(
  File "C:\pkservices\docker\.venv\lib\site-packages\pysnmp\entity\rfc3413\cmdgen.py", line 76, in processResponsePdu
    errorIndication = statusInformation["errorIndication"]
  File "C:\pkservices\docker\.venv\lib\site-packages\pysnmp\proto\error.py", line 36, in __getitem__
    return self.__errorIndication[key]
KeyError: 'errorIndication'
```

**Comment by lextm** [comment]
Cannot reproduce the issue, so you need to provide more details.
