### ISSUE TITLE
TypeError: MyStaticMibScalarInstance.getValue() got an unexpected keyword argument 'snmpEngine'

### ISSUE THREAD

**Issue by miguel-slc** [lextudio/pysnmp#136]
### Expected behavior

When running the example available in the documentation ([agent-side-mib-implementations#agent-side-mib-implementations](agent-side-mib-implementations#agent-side-mib-implementations)), I should be able to retrieve the value defined in the function getValue (class MyStaticMibScalarInstance)

### Actual behavior

When running the example, I get the following error:
TypeError: MyStaticMibScalarInstance.getValue() got an unexpected keyword argument 'snmpEngine'

### Detailed steps

Once the script is running, I performed the following command:
snmpget -v 2c -c public 127.0.0.1:20161 1.3.6.5.1.0

### Python package information

certifi            2024.7.4 cffi               1.17.0 charset-normalizer 3.3.2 cryptography       43.0.0 idna               3.8 Jinja2             3.1.4 MarkupSafe         2.1.5 pip                24.2 ply                3.11 pyasn1             0.6.0 pycparser          2.22 pysmi              1.5.4 pysnmp             7.1.8 pysnmpcrypto       0.0.4 requests           2.32.3 setuptools         59.6.0 snmpsim            1.1.7 urllib3            2.2.2

### Operating system information

Linux

### Python information

3.10.12

### Relevant log output

```shell
Exception in callback AbstractTransportDispatcher._callback_function(<pysnmp.carri...x7f000cec6110>, ('127.0.0.1', 49032), b'0&\x02\x01\...1\x00\x05\x00')
handle: <Handle AbstractTransportDispatcher._callback_function(<pysnmp.carri...x7f000cec6110>, ('127.0.0.1', 49032), b'0&\x02\x01\...1\x00\x05\x00')>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/test/.venv/lib/python3.10/site-packages/pysnmp/carrier/base.py", line 166, in _callback_function
    self.__recv_callables[recvId](
  File "/home/test/.venv/lib/python3.10/site-packages/pysnmp/entity/engine.py", line 225, in __receive_message_callback
    self.message_dispatcher.receive_message(
  File "/home/test/.venv/lib/python3.10/site-packages/pysnmp/proto/rfc3412.py", line 561, in receive_message
    processPdu(
  File "/home/test/.venv/lib/python3.10/site-packages/pysnmp/entity/rfc3413/cmdrsp.py", line 212, in process_pdu
    self.handle_management_operation(
  File "/home/test/.venv/lib/python3.10/site-packages/pysnmp/entity/rfc3413/cmdrsp.py", line 352, in handle_management_operation
    rspVarBinds = mgmtFun(*varBinds, **context)
  File "/home/test/.venv/lib/python3.10/site-packages/pysnmp/smi/instrum.py", line 280, in read_variables
    return self.flip_flop_fsm(self.fsm_read_variable, *varBinds, **context)
  File "/home/test/.venv/lib/python3.10/site-packages/pysnmp/smi/instrum.py", line 244, in flip_flop_fsm
    rval = mgmtFun((tuple(name), val), **context)
  File ".py", line 474, in readGet
  File ".py", line 670, in readGet
  File ".py", line 812, in readGet
TypeError: MyStaticMibScalarInstance.getValue() got an unexpected keyword argument 'snmpEngine'
```

**Comment by lextudio-support** [comment]
New issues are marked as low priority by default. [Becoming our commercial customers](https://www.pysnmp.com/support#commercial-support), and then your reports are handled with higher priority after triage.

**Comment by lextm** [comment]
While we might investigate further on what's wrong, you might use the following workaround,

``` python
"""
Implementing scalar MIB objects
+++++++++++++++++++++++++++++++

Listen and respond to SNMP GET/SET/GETNEXT/GETBULK queries with
the following options:

* SNMPv2c
* with SNMP community "public"
* serving custom Managed Object Instance defined within this script
* allow read access only to the subtree where the custom MIB object resides
* over IPv4/UDP, listening at 127.0.0.1:161

The following Net-SNMP commands will walk this Agent:

| $ snmpwalk -v2c -c public 127.0.0.1 .1.3.6

"""  #
import sys
from pysnmp.entity import engine, config
from pysnmp.entity.rfc3413 import cmdrsp, context
from pysnmp.carrier.asyncio.dgram import udp
from pysnmp.proto.api import v2c

# Create SNMP engine
snmpEngine = engine.SnmpEngine()

# Transport setup

# UDP over IPv4
config.add_transport(
    snmpEngine, udp.DOMAIN_NAME, udp.UdpTransport().open_server_mode(("127.0.0.1", 1610))
)

# SNMPv2c setup

# SecurityName <-> CommunityName mapping.
config.add_v1_system(snmpEngine, "my-area", "public")

# Allow read MIB access for this user / securityModels at VACM
config.add_vacm_user(snmpEngine, 2, "my-area", "noAuthNoPriv", (1, 3, 6, 5))

# Create an SNMP context
snmpContext = context.SnmpContext(snmpEngine)

# --- create custom Managed Object Instance ---

mibBuilder = snmpContext.get_mib_instrum().get_mib_builder()

MibScalar, MibScalarInstance = mibBuilder.import_symbols(
    "SNMPv2-SMI", "MibScalar", "MibScalarInstance"
)

InstanceName = MibScalar((1, 3, 6, 5, 1), v2c.OctetString())

__MyStaticMibScalarInstance = MibScalarInstance(
    InstanceName.name, (0,), InstanceName.syntax.clone(
            f"Python {sys.version} running on a {sys.platform} platform"
        )
)

from pysnmp import debug

debug.set_logger(debug.Debug('all'))


mibBuilder.export_symbols(
    "__MY_MIB",
    InstanceName,
    __MyStaticMibScalarInstance,
)

# --- end of Managed Object Instance initialization ----

# Register SNMP Applications at the SNMP engine for particular SNMP context
cmdrsp.GetCommandResponder(snmpEngine, snmpContext)
cmdrsp.NextCommandResponder(snmpEngine, snmpContext)
cmdrsp.BulkCommandResponder(snmpEngine, snmpContext)

# Register an imaginary never-ending job to keep I/O dispatcher running forever
snmpEngine.transport_dispatcher.job_started(1)

# Run I/O dispatcher which would receive queries and send responses
try:
    snmpEngine.open_dispatcher()
except:
    snmpEngine.close_dispatcher()
    raise

```

**Comment by lextm** [comment]
The sample code was incorrect, and just fixed,

https://docs.lextudio.com/pysnmp/v7.1/examples/smi/agent/implementing-mib-objects

**Comment by mobregon** [comment]
Thanks so much for the quick fix! It works now.
