### ISSUE TITLE
Fresh install of snmpfwd crashes dependent on pysnmp.carrier.asynsock

### ISSUE THREAD

**Issue by robertdistel** [lextudio/pysnmp#153]
### Expected behavior

Installed according to https://docs.lextudio.com/pysnmp/v7.1/ documentation..
python3.11 -m pip install --proxy="http://172.30.18.2:3128/" --upgrade pip
 1113  pip install --proxy="http://172.30.18.2:3128/" pysnmp
 1114  pip install --proxy="http://172.30.18.2:3128/" snmpclitools
 1115  pip install --proxy="http://172.30.18.2:3128/" snmpfwd

Cli tools where succesfully installed. snmpget works correctly against a test box using snmpv2
(pysnmp.11) [root@logger bin]#  snmpget -v2c -On -c grafana linux-test-box .1.3.6.1.4.1.2021.100.6.0
Press Ctrl-C to stop.
1.3.6.1.4.1.2021.100.6.0 = OctetString:  '--build=x86_64-redhat-linux-gnu' '--host=x86_64-redhat-linux-gnu' '--program-prefix=' '--disable-dependency-tracking' '--prefix=/usr' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--datadir=/usr/share' '--includedir=/usr/include' '--libdir=/usr/lib64' '--libexecdir=/usr/libexec' '--localstatedir=/var' '--sharedstatedir=/var/lib' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--disable-static' '--enable-shared' '--enable-as-needed' '--enable-blumenthal-aes' '--enable-embedded-perl' '--enable-ipv6' '--enable-local-smux' '--enable-mfd-rewrites' '--enable-ucd-snmp-compatibility' '--disable-des' '--sysconfdir=/etc' '--with-cflags=-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64-v2 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protect
^CShutting down...
Environment 
(pysnmp.11) [root@logger bin]# python -V
Python 3.11.5
(pysnmp.11) [root@logger bin]# pip list
Package            Version
------------------ ---------
certifi            2024.8.30
cffi               1.17.1
charset-normalizer 3.4.0
cryptography       44.0.0
idna               3.10
Jinja2             3.1.4
MarkupSafe         3.0.2
pip                24.3.1
ply                3.11
pyasn1             0.6.1
pycparser          2.22
pysmi              1.5.9
pysnmp             6.2.6
pysnmpcrypto       0.0.4
requests           2.32.3
setuptools         65.5.1
snmpclitools       0.7.2
snmpfwd            0.4.5
urllib3            2.2.3
Continue according to https://docs.lextudio.com/snmpfwd/
snmpfwd-server --help

I expect to see something like 
$ snmpfwd-server.py --help
Usage: snmpfwd-server.py
    [--help]
    [--version]
    [--debug-snmp=<options>]
    [--debug-asn1=<options>]
    [--daemonize]
    [--process-user=<uname>] [--process-group=<gname>]
    [--pid-file=<file>]
    [--logging-method=<options>]
    [--log-level=<options>]
    [--config-file=<file>]

as in the documents

### Actual behavior

What actually happens is 
(pysnmp.11) [root@logger bin]# snmpfwd-server --help
Traceback (most recent call last):
  File "/root/pysnmp.11/bin/snmpfwd-server", line 5, in <module>
    from snmpfwd.scripts.snmpfwdserver import main
  File "/root/pysnmp.11/lib64/python3.11/site-packages/snmpfwd/scripts/snmpfwdserver.py", line 19, in <module>
    from pysnmp.carrier.asynsock.dgram import udp
ModuleNotFoundError: No module named 'pysnmp.carrier.asynsock'

### Detailed steps

Install snmpfwd thourgh pip

python3.11 -m venv pysnmp.11
python3.11 -m pip install --proxy="http://172.30.18.2:3128/" --upgrade pip
pip install --proxy="http://172.30.18.2:3128/" pysnmp
pip install --proxy="http://172.30.18.2:3128/" snmpclitools
pip install --proxy="http://172.30.18.2:3128/" snmpfwd

Attempt to run help
snmpfwd-server.py --help

### Python package information

snmpfwd            0.4.5

### Operating system information

RHEL 9.3

### Python information

3.11.5

### Relevant log output

```shell
-bash: snmpfwd-server.py: command not found
(pysnmp.11) [root@logger bin]# snmpfwd-server --help
Traceback (most recent call last):
  File "/root/pysnmp.11/bin/snmpfwd-server", line 5, in <module>
    from snmpfwd.scripts.snmpfwdserver import main
  File "/root/pysnmp.11/lib64/python3.11/site-packages/snmpfwd/scripts/snmpfwdserver.py", line 19, in <module>
    from pysnmp.carrier.asynsock.dgram import udp
ModuleNotFoundError: No module named 'pysnmp.carrier.asynsock'
```

**Comment by lextudio-support** [comment]
New issues are marked as low priority by default. [Becoming our commercial customers](https://www.pysnmp.com/support#commercial-support), and then your reports are handled with higher priority after triage.

**Comment by lextudio-support** [comment]
New issues are marked as low priority by default. [Becoming our commercial customers](https://www.pysnmp.com/support#commercial-support), and then your reports are handled with higher priority after triage.

**Comment by lextm** [comment]
We notice that a pull request has been opened for this https://github.com/lextudio/snmpfwd/pull/1.

There might be more changes needed to make snmpfwd work properly with latest pysnmp versions, and we welcome more community contributions in this area.

**Comment by marshallmassengill** [comment]
There are indeed more changes that are needed.  I'm a bit out of my depth with python programming (though I'm trying) but for a future person to pick this up, I've identified a few things that definitely need updates:

In snmpfwdclient.py  snmpfwdserver.py, there are updates that must be made to account for how Asyncio works, specifically around the transportDispatcher usage.

In crypto.py, there are updates that need to be made for the Crypto module and to remove all of the old conversions for strings and octets that have been removed from pyasn1.  This one should be an easy update, it's mostly removing old code.

In server.py and client.py, there are updates that are needed to remove asyncore.

That's what I know about so far.  I'm slowly trying to work through these and if I get anywhere then I'll share it.  It's definitely more work than the PR here would suggest.  Thanks to the lexstudio folks for keeping these projects alive.
