### ISSUE TITLE
 pip install git+https://github.com/lextudio/pysnmp.git, install  fail 

### ISSUE THREAD

**Issue by feng99** [lextudio/pysnmp#155]
### Expected behavior

I expected this, install success

### Actual behavior

But a bug happened like this,
![image](https://github.com/user-attachments/assets/b5e573c3-0e19-466b-899f-2f7b7875814a)

### Detailed steps

The steps are,
1: pip uninstall pysnmp    
because this is another git project, version is V4.+, I want install V7.+

2.pip install git+https://github.com/lextudio/pysnmp.git

### Python package information

no

### Operating system information

windows10

### Python information

v3.6

### Relevant log output

```shell
pip install git+https://github.com/lextudio/pysnmp.git
Collecting git+https://github.com/lextudio/pysnmp.git
  Cloning https://github.com/lextudio/pysnmp.git to c:\users\11463\appdata\local\temp\pip-req-build-vn1duqb0
  Running command git clone --filter=blob:none -q https://github.com/lextudio/pysnmp.git 'C:\Users\11463\AppData\Local\Temp\pip-req-build-vn1duqb0'
  Resolved https://github.com/lextudio/pysnmp.git to commit e7b7f80b0fd98154ece2ec0e5a42ea50811db7ad
ss\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\11463\AppData\Local\Temp\tmplsnoz7fl'
       cwd: C:\Users\11463\AppData\Local\Temp\pip-req-build-vn1duqb0
  Complete output (14 lines):
  Traceback (most recent call last):
 File "c:\users\11463\appdata\local\programs\python\python36\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
      main()
    File "c:\users\11463\appdata\local\programs\python\python36\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "c:\users\11463\appdata\local\programs\python\python36\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py",

 File "C:\Users\11463\AppData\Local\Temp\pip-build-env-kd128tx6\overlay\Lib\site-packages\poetry\core\masonry\api.py", line 43, in prepare_metadata_for_build_wheel
      poetry = Factory().create_poetry(Path(".").resolve(), with_dev=False)
    File "C:\Users\11463\AppData\Local\Temp\pip-build-env-kd128tx6\overlay\Lib\site-packages\poetry\core\factory.py", line 43, in create_poetry
      raise RuntimeError("The Poetry configuration is invalid:\n" + message)
  RuntimeError: The Poetry configur

 ----------------------------------------
WARNING: Discarding git+https://github.com/lextudio/pysnmp.git. Command errored out with exit status 1: 'c:\users\11463\appdata\local\programs\python\python36\python.exe' 'c:\users\11463\appdata\local\programs\python\python36\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\11463\AppData\Local\Temp\tmplsnoz7fl' Check the logs for full command output.
ERROR: Command errored out with exit status 1
```

**Comment by lextudio-support** [comment]
New issues are marked as low priority by default. [Becoming our commercial customers](https://www.pysnmp.com/support#commercial-support), and then your reports are handled with higher priority after triage.

**Comment by lextm** [comment]
Python 3.6 reached end of life long ago.

**Comment by feng99** [comment]
> Python 3.6 reached end of life long ago.
The python version of my current project cannot be changed for some reason. What should I do?
thanks for you

**Comment by lextm** [comment]
That's now a question this repo can answer. It started for Python 3.7+ and now requires 3.9+.
