### ISSUE TITLE
Python 3.11 import Mapping from collections error

### ISSUE THREAD

**Issue by EDKarlsson** [lextudio/pysnmp#20]
I'm running an example very close to what is on the read me using an MIB for a power sensor. I've tested the code using python3.8 and python 3.10 and it works with no issues. However, it looks like the current version of pysnmp can't be used with 3.11 because of `Mapping` no longer being in the `collections` module. The import statement needs to be `from collections.abc import Mapping`.
 
```shell
➜  snmp python3.8 src/btg_driver.py
MIBs analyzed 4, MIBs failed 0
BTG-MIB::sensorPower.0 = 2.1
BTG-MIB::sensorReflectedPower.0 = 0.2
BTG-MIB::sensorVSWR.0 = 1.91
```

```shell
➜  snmp python3.11 src/btg_driver.py
Traceback (most recent call last):
  File "/home/edkarlsson/git/sandbox/snmp/src/btg_driver.py", line 74, in <module>
    error_indication, error_status, error_index, var_binds = next(iterator)
                                                             ^^^^^^^^^^^^^^
  File "/home/edkarlsson/.local/lib/python3.11/site-packages/pysnmp/hlapi/asyncore/sync/cmdgen.py", line 100, in getCmd
    cmdgen.getCmd(snmpEngine, authData, transportTarget,
  File "/home/edkarlsson/.local/lib/python3.11/site-packages/pysnmp/hlapi/asyncore/cmdgen.py", line 130, in getCmd
    vbProcessor.makeVarBinds(snmpEngine, varBinds), __cbFun,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/edkarlsson/.local/lib/python3.11/site-packages/pysnmp/hlapi/varbinds.py", line 39, in makeVarBinds
    __varBinds.append(varBind.resolveWithMib(mibViewController, ignoreErrors=False))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/edkarlsson/.local/lib/python3.11/site-packages/pysnmp/smi/rfc1902.py", line 850, in resolveWithMib
    self.__args[0].resolveWithMib(mibViewController)
  File "/home/edkarlsson/.local/lib/python3.11/site-packages/pysnmp/smi/rfc1902.py", line 361, in resolveWithMib
    addMibCompiler(
  File "/home/edkarlsson/.local/lib/python3.11/site-packages/pysnmp/smi/compiler.py", line 38, in addMibCompiler
    raise error.SmiError('MIB compiler not available: %s' % errorMsg)
pysnmp.smi.error.SmiError: MIB compiler not available: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.11/collections/__init__.py)```

**Comment by EDKarlsson** [comment]
I'd create a PR with a backwards compatible fix but I'm at work and am unable to commit to public repos.

**Comment by lextm** [comment]
Cannot reproduce this. Wait for more information.
