### ISSUE TITLE
[Bug]: PySMI generates unusable Python representations of MIBs

### ISSUE THREAD

**Issue by eiderdaus** [lextudio/pysnmp#57]
### Expected behavior

I expected the MIB compiler to automatically produce a valid Python representation of a given MIB when using the `ObjectType`'s `addAsn1MibSource` mechanism.

### Actual behavior

The call to `ObjectType(ObjectIdentity('IF-MIB', 'ifName').addAsn1MibSource(...))` works fine. Only when executing an SNMP command, in my case `bulkCmd()`, I get the following output:

```
MIBs analyzed 6, MIBs failed 0
Traceback (most recent call last):
  File "C:\Users\eiderdaus\AppData\Roaming\Python\Python312\site-packages\pysnmp\smi\builder.py", line 417, in loadModules
    self.loadModule(modName, **userCtx)
  File "C:\Users\eiderdaus\AppData\Roaming\Python\Python312\site-packages\pysnmp\smi\builder.py", line 393, in loadModule
    raise error.MibNotFoundError(
pysnmp.smi.error.MibNotFoundError: MIB file "IF-MIB.py[co]" not found in search path (DirMibSource('C:\\Users\\eiderdaus\\AppData\\Roaming\\Python\\Python312\\site-packages\\pysnmp\\smi\\mibs'), DirMibSource('C:\\Users\\eiderdaus\\AppData\\Roaming\\Python\\Python312\\site-packages\\pysnmp\\smi\\mibs\\instances'), DirMibSource('pysnmp_mibs'), DirMibSource('C:\\Users\\eiderdaus\\PySNMP Configuration\\mibs'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\tools\mibtest.py", line 17, in <module>
    asyncio.run(run())
  File "C:\Program Files\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\asyncio\base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\tools\mibtest.py", line 7, in run
    errorIndication, errorStatus, errorIndex, varBinds = await bulkCmd(
                                                         ^^^^^^^^^^^^^^
  File "C:\Users\eiderdaus\AppData\Roaming\Python\Python312\site-packages\pysnmp\hlapi\asyncio\cmdgen.py", line 609, in bulkCmd
    vbProcessor.makeVarBinds(snmpEngine, varBinds),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eiderdaus\AppData\Roaming\Python\Python312\site-packages\pysnmp\hlapi\varbinds.py", line 41, in makeVarBinds
    varBind.resolveWithMib(mibViewController, ignoreErrors=False)
  File "C:\Users\eiderdaus\AppData\Roaming\Python\Python312\site-packages\pysnmp\smi\rfc1902.py", line 931, in resolveWithMib
    self.__args[0].resolveWithMib(mibViewController)
  File "C:\Users\eiderdaus\AppData\Roaming\Python\Python312\site-packages\pysnmp\smi\rfc1902.py", line 500, in resolveWithMib
    (mibNode,) = mibViewController.mibBuilder.importSymbols(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eiderdaus\AppData\Roaming\Python\Python312\site-packages\pysnmp\smi\builder.py", line 464, in importSymbols
    self.loadModules(modName, **userCtx)
  File "C:\Users\eiderdaus\AppData\Roaming\Python\Python312\site-packages\pysnmp\smi\builder.py", line 440, in loadModules
    self.loadModule(modName, **userCtx)
  File "C:\Users\eiderdaus\AppData\Roaming\Python\Python312\site-packages\pysnmp\smi\builder.py", line 350, in loadModule
    codeObj, sfx = mibSource.read(modName)
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eiderdaus\AppData\Roaming\Python\Python312\site-packages\pysnmp\smi\builder.py", line 148, in read
    return compile(modData, pyPath, "exec"), pyPath
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eiderdaus\PySNMP Configuration\mibs\IF-MIB.py", line 1
    """SNMP MIB module (IF-MIB) expressed in pysnmp data model.
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 233-234: truncated \UXXXXXXXX escape
```

### Detailed steps

The above output refers to the following code, but the error also happens with the synchronous API as well:

```
import asyncio
from pysnmp.hlapi.asyncio import *

mib_path = 'file://C:/Users/eiderdaus/tools/mibs.pysnmp.com/asn1'

async def run():
    errorIndication, errorStatus, errorIndex, varBinds = await bulkCmd(
        SnmpEngine(),
        CommunityData('public'),
        UdpTransportTarget(('demo.pysnmp.com', 161)),
        ContextData(),
        0, 2,
        ObjectType(ObjectIdentity('IF-MIB', 'ifName').addAsn1MibSource(mib_path)),
    )
    print(errorIndication, errorStatus, errorIndex, varBinds)

asyncio.run(run())
```

I used a fresh copy of the mibs.pysnmp.com repository. The reason for the error is the docstring that appears in the beginning of the generated Python module:

```
"""SNMP MIB module (IF-MIB) expressed in pysnmp data model.

This Python module is designed to be imported and executed by the
pysnmp library.

See https://www.pysnmp.com/pysnmp for further information.

Notes
-----
ASN.1 source file://\Users\eiderdaus\Documents\tools\mibs.pysnmp.com\asn1\IF-MIB
Produced by pysmi-1.3.3 at Thu Mar 14 21:21:17 2024
On host ? platform ? version ? by user ?
Using Python version 3.12.2 (tags/v3.12.2:6abddd9, Feb  6 2024, 21:26:36) [MSC v.1937 64 bit (AMD64)]
"""
```

It contains a `\U` not followed by a valid unicode escape sequence, therefore making the docstring invalid.

The old `pysnmp==4.4.12` and `pysmi==0.3.4` (which bring a whole lot of other problems, of course) do not seem to produce this bug, because the generated Python code is different. It contains the same source file path, but contained in a normal `#` Python comment, not a docstring. However I could not find which commit exactly introduced this change.

Simply replacing any ocurrence of `\` with `/` in the displayed path should fix the issue for the most part. Then, the shown path might not be correct in general because paths in Unix-like operating systems might actually contain backslashes. And it might also not fix the issue for every path, as paths might also contain `"""` or other stuff which might break things again. Showing the `repr()` of the URL and somehow escaping `"""` might be safe but also ugly. Nevertheless these are just my thoughts - I do not think I am up to decide how to fix this bug.

Thank you for your work, it is very useful!

### Python package information

pysmi-lextudio==1.3.3, pysnmp-lextudio==6.0.10

### Operating system information

Windows 10

### Python information

3.12.2

**Comment by lextm** [comment]
Couldn't reproduce this issue yet.

**Comment by eiderdaus** [comment]
No, I need more info from _you_ ;-) When generating IF-MIB.py under Windows with an absolute folder path like I did, what output do you get? Do you get forward slashes in the docstring? It should be really straightforward to reproduce this issue, as long as you have access to a Windows machine. Note however that you might need to clear your `%USERPROFILE%\PySNMP Configuration` directory; otherwise a preexisting IF-MIB.py might be used and no new one generated.

**Comment by lextm** [comment]
I see. You can now try `pysmi-lextudio` 1.3.4. This issue should have been resolved.
