### ISSUE TITLE
[Bug]: pysmi's mibdump no longer supports generating PySNMP code for MIB instances

### ISSUE THREAD

**Issue by grondman** [lextudio/pysnmp#62]
### Expected behavior

I expect the `mibdump` tool to be able to generate code for MIB instances, as explained at https://docs.lextudio.com/snmpresponder/mib-implementation/.

### Actual behavior

The flag used in the docs (`--destination-template`) no longer exists in the current implementation of `mibdump` (pysmi-lextudio 1.4.2). The source for `mibdump` which converts to PySNMP output still shows the use of a `dstTemplate` variable, but there's no longer any way to set it through the regular `mibdump` tool.

Is it still possible to generate code for MIB instances at all with `mibdump` or is it advised to simply write it yourself?

### Python package information

1.4.2

### Operating system information

Ubuntu 22.04.04 LTS

### Python information

3.12.1

**Comment by lextm** [comment]
We found this both a documentation issue and code merge issue. Will work on it later.

**Comment by lextm** [comment]
PySMI 1.4.3 was just released with the missing command line switch. You might test if that helps.

The documentation is still out-of-date, and we will see into that in the coming weeks.

**Comment by desultory** [comment]
I'm not able to generate new pysnmp usable mibs, is it related to this? I tried following: https://github.com/lextudio/pysnmp/blob/main/examples/smi/manager/mib-tree-inspection.py

**Comment by desultory** [comment]
I tested with  `mibdump --destination-format pysnmp --destination-template pysnmp/mib-instrumentation/managed-objects-instances.j2 .snmp/mibs/mikrotik.mib`

Then copied the generated MIB to: /usr/lib/python3.12/site-packages/pysnmp/smi/mibs/MIKROTIK-MIB.py but get:

loadModule: read __SNMP-FRAMEWORK-MIB from DirMibSource('/usr/lib/python3.12/site-packages/pysnmp/smi/mibs') failed: [Errno 2] No suitable module found: '__SNMP-FRAMEWORK-MIB'

Is there a straightforward way to take a working MIB and use it with pysnmp?

**Comment by desultory** [comment]
The generated MIB seems to have issues:

```
 mtxrWlStatTxCCQ,
 mtxrWlStatTxRate) = mibBuilder.importSymbols(
    #"MIKROTIK-MIB",
    "mtxrAltitude",
```

I'm not sure if that is intentional, but it is set to import itself, which is done by load_module, and it fails because it's not already imported.

I commented it out, but it still won't import:

```
Loading MIB: MIKROTIK-MIB from: DirMibSource('/usr/lib/python3.12/site-packages/pysnmp/smi/mibs')
Loading module symbols: SNMPv2-SMI
Loading module symbols: mtxrAltitude
Loading MIB: mtxrAltitude from: DirMibSource('/usr/lib/python3.12/site-packages/pysnmp/smi/mibs')
loadModule: read mtxrAltitude from DirMibSource('/usr/lib/python3.12/site-packages/pysnmp/smi/mibs') failed: [Errno 2] No suitable module found: 'mtxrAltitude'
Loading MIB: mtxrAltitude from: DirMibSource('/usr/lib/python3.12/site-packages/pysnmp/smi/mibs/instances')
loadModule: read mtxrAltitude from DirMibSource('/usr/lib/python3.12/site-packages/pysnmp/smi/mibs/instances') failed: [Errno 2] No suitable module found: 'mtxrAltitude'
Loading MIB: mtxrAltitude from: DirMibSource('pysnmp_mibs')
loadModule: read mtxrAltitude from DirMibSource('pysnmp_mibs') failed: [Errno 2] No suitable module found: 'mtxrAltitude'
{'ASN1': '/usr/lib/python3.12/site-packages/pysnmp/smi/mibs/ASN1.py', 'ASN1-ENUMERATION': '/usr/lib/python3.12/site-packages/pysnmp/smi/mibs/ASN1-ENUMERATION.py', 'ASN1-REFINEMENT': '/usr/lib/python3.12/site-packages/pysnmp/smi/mibs/ASN1-REFINEMENT.py', 'SNMPv2-SMI': '/usr/lib/python3.12/site-packages/pysnmp/smi/mibs/SNMPv2-SMI.py', 'SNMPv2-CONF': '/usr/lib/python3.12/site-packages/pysnmp/smi/mibs/SNMPv2-CONF.py', 'SNMPv2-TC': '/usr/lib/python3.12/site-packages/pysnmp/smi/mibs/SNMPv2-TC.py', 'SNMPv2-MIB': '/usr/lib/python3.12/site-packages/pysnmp/smi/mibs/SNMPv2-MIB.py', 'SNMP-MPD-MIB': '/usr/lib/python3.12/site-packages/pysnmp/smi/mibs/SNMP-MPD-MIB.py', 'SNMP-FRAMEWORK-MIB': '/usr/lib/python3.12/site-packages/pysnmp/smi/mibs/SNMP-FRAMEWORK-MIB.py', 'SNMP-TARGET-MIB': '/usr/lib/python3.12/site-packages/pysnmp/smi/mibs/SNMP-TARGET-MIB.py', 'SNMP-COMMUNITY-MIB': '/usr/lib/python3.12/site-packages/pysnmp/smi/mibs/SNMP-COMMUNITY-MIB.py', 'SNMP-USER-BASED-SM-MIB': '/usr/lib/python3.12/site-packages/pysnmp/smi/mibs/SNMP-USER-BASED-SM-MIB.py', '__SNMP-FRAMEWORK-MIB': '/usr/lib/python3.12/site-packages/pysnmp/smi/mibs/instances/__SNMP-FRAMEWORK-MIB.py'}
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/pysnmp/smi/builder.py", line 364, in load_module
    runpy.run_path(
  File "<frozen runpy>", line 287, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/lib/python3.12/site-packages/pysnmp/smi/mibs/MIKROTIK-MIB.py", line 419, in <module>
    mtxrWlStatTxRate) = mibBuilder.importSymbols(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pysnmp/smi/builder.py", line 462, in import_symbols
    self.load_modules(modName, **userCtx)
  File "/usr/lib/python3.12/site-packages/pysnmp/smi/builder.py", line 410, in load_modules
    self.load_module(modName, **userCtx)
  File "/usr/lib/python3.12/site-packages/pysnmp/smi/builder.py", line 386, in load_module
    raise error.MibNotFoundError(
pysnmp.smi.error.MibNotFoundError: MIB file "mtxrAltitude.py[co]" not found in search path (DirMibSource('/usr/lib/python3.12/site-packages/pysnmp/smi/mibs'), DirMibSource('/usr/lib/python3.12/site-packages/pysnmp/smi/mibs/instances'), DirMibSource('pysnmp_mibs'))
```

**Comment by lextm** [comment]
@desultory you will have to report a new issue instead, as it is irrelevant to this item. Besides, cannot reproduce what you described.
